### PR TITLE
Tests, app and installer for Windows

### PR DESCRIPTION
**Pull request by vlastahajek**
Complete portation of MF to Windows. 
This PR fixes:
#944 - 
#945 
#417 (verified) Windows
and many others

### CODE REVIEW

**Comment by dvorka** [comment]
Let me try to make it green before merging.

**Comment by vlastahajek** [comment]
```
[==========] 72 tests from 15 test cases ran. (458 ms total)
[  PASSED  ] 71 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MarkdownParserTestCase.Deadline
```
On my Ubuntu 18.04 VM image all tests pass. How to get full test log from Travis?

**Comment by vlastahajek** [comment]
Closing this PR until everything is green, to save CI resources.

**Comment by dvorka** [comment]
Excellent job @vlastahajek :tada: :+1: :tada:

**Pull request merged**
